### ISSUE TITLE
Accessibility

### ISSUE THREAD

**Issue by ChrisBrownie55** [gwenf/freecodecamp-projects-vue#6]
I'm watching the live stream on YouTube but unable to leave comments during the video so I'll put this here.

# `<div>`s should not be used as a replacement for `<button>`s

This requires lots of a11y work to make the `<div>` appear as a `<button>` to all kinds of users (keyboard, screenreader, etc). To make this easier you can simply remove all styles from the `<button>` that you are working with to start anew with your styles (as though it were a `<div>`).

**Comment by ChrisBrownie55** [comment]
This is in reference to the "Drum Machine" project during this video: https://www.youtube.com/watch?v=0b5T7wYDV5o

**Comment by ChrisBrownie55** [comment]
https://github.com/gwenf/freecodecamp-projects-vue/blob/b6914dd7969b21928e2c7320cb482d9ecd097103/drum-machine/drum-app/src/App.vue#L30-L38

**Comment by gwenf** [comment]
Thank you for the advice @ChrisBrownie55
